name: Generate Snake Animation

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"
  
  # Allows manual workflow triggering
  workflow_dispatch:
  
  # Runs on push to main branch
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ElySimp
          # The generated svg will be available as artifact in the workflow
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Push the content of dist folder to a branch named output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
